apiVersion: apps/v1
kind: Deployment
metadata:
  name: moregoat-backend-deployment
  labels:
    app: moregoat-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moregoat-server
  template:
    metadata:
      labels:
        app: moregoat-server
    spec:
      containers:
      - name: moregoat-backend
        image: vitkovec/moregoat-backend:latest
        ports:
        - containerPort: 5000
          name: backend-port
---
apiVersion: v1
kind: Service
metadata:
  name: moregoat-server-service
spec:
  selector:
    app: moregoat-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: backend-port
  type: ClusterIP
